name: Build and deploy to GitHub Pages

on:
    push:
        branches: [master]

jobs:
    deploy-to-github-pages:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
  
          - name: Setup .NET Core SDK
            uses: actions/setup-dotnet@v1
            with:
              dotnet-version: 7.0.103
  
          - name: Publish .NET Core Project
            run: dotnet publish WebAssemblyTest/WebAssemblyTest.csproj -c Release -o release --nologo
  
          - name: Copy index.html to 404.html
            run: cp release/wwwroot/index.html release/wwwroot/404.html
  
          - name: Add .nojekyll file
            run: touch release/wwwroot/.nojekyll
  
          - name: Commit wwwroot to GitHub Pages
            uses: JamesIves/github-pages-deploy-action@3.7.1
            with:
              GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
              BRANCH: gh-pages
              FOLDER: release/wwwroot
